---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  # type: LoadBalancer
  # externalTrafficPolicy: Local
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    service: ambassador
