Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    (0..2).each do |i|
        config.vm.define "k8s#{i}" do |node|
            node.vm.box = "ubuntu/xenial64"
            node.vm.hostname = "k8s#{i}"
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}", netmask: "255.255.255.0"
            node.vm.provider "virtualbox" do |v|
                v.name = "k8s#{i}"
                v.memory = 1024
                v.gui = false
            end        
            node.vm.provision :shell, inline: "sed 's/127\.0\.1\.1.*k8s.*/192\.168\.50\.#{i + 10} k8s#{i}/' -i /etc/hosts"
        end
    end
end