Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    (0..2).each do |i|
        config.vm.define "k8s#{i}" do |node|
            node.vm.box = "ubuntu/xenial64"
            node.vm.hostname = "k8s#{i}"
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}", netmask: "255.255.255.0"
            node.vm.provider "virtualbox" do |v|
                v.name = "k8s#{i}"
                v.memory = 1024
                v.gui = false
            end
            node.vm.provision :shell, inline: "sed 's/127\.0\.1\.1.*k8s.*/192\.168\.50\.#{i + 10} k8s#{i}/' -i /etc/hosts"
            node.vm.provision "ansible" do |ansible|
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                }
                ansible.playbook = "kubernetes-setup/common-playbook.yml"
            end
            node.vm.provision "ansible" do |ansible|
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                }
                if i == 0
                    ansible.playbook = "kubernetes-setup/master-playbook.yml"
                else
                    ansible.playbook = "kubernetes-setup/node-playbook.yml"
                end
            end
        end
    end
end