---
- hosts: all
  become: true
  environment:
    PYTHONIOENCODING: utf8
  tasks:

    - name: 创建集群
      command: kubeadm init --apiserver-advertise-address="{{ node_ip }}" --service-cidr=10.96.0.0/12 --pod-network-cidr=10.32.0.0/16

    - name: 非root用户的配置
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - chown vagrant:vagrant /home/vagrant/.kube/config

    - name: 添加网络插件： Weave Net
      become: false
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

    - name: 创建token及加入集群的命令
      command: kubeadm token create --print-join-command
      register: join_command

    - name: 保存加入集群的命令到本地（宿主机）
      become: false
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  # handlers:
  #   - name: docker status
  #     service: name=docker state=started
