apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  # this setting is t make sure the source IP address is preserved.
  # NodePort方式 可以添加以下两个参数
  # externalTrafficPolicy: Local
  # externalIPs:
  #   - 192.168.50.10
  #   - 192.168.50.11
  #   - 192.168.50.12
  # 注意不同类型，访问方式不同
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

---

