apiVersion: v1
kind: Secret
metadata:
  name: harry-apikey
type: Opaque
stringData:
  kongCredType: key-auth
  key: my-sooper-secret-key
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: harry
username: harry
credentials:
  - harry-apikey
